### PR TITLE
cmake: check which GMime version notmuch is compiled against

### PR DESCRIPTION
**Pull request by gauteh**

### CODE REVIEW

**Comment by gauteh** [comment]
@c-alpha: could you take a look on this one

**Comment by gauteh** [comment]
This could probably be improved to check that the exact version match.

**Comment by c-alpha** [comment]
> @c-alpha: could you take a look on this one

Headscratcher... **Will do!**

**Comment by gauteh** [comment]
Nice, when we have this one sorted out I will make a minor release to fix the latest issues. Will remove SCons after that I think.

**Comment by c-alpha** [comment]
Ok, I've made a `FindNotmuch.cmake` module, which sets the following variables:
```
#  Notmuch_FOUND          - system has Notmuch
#  Notmuch_VERSION        - the version of the Notmuch shared library
#  Notmuch_INCLUDE_DIRS   - the Notmuch include directories
#  Notmuch_LIBRARIES      - link these to use Notmuch
#  Notmuch_GMIME_VERSION  - the GMime version notmuch was linked against
#  Notmuch_INDEX_FILE_API - whether Notmuch has the notmuch_database_index_file() API
```
Many thanks for the `GetPrerequisites` pointer! Now updating the `CMakeLists.txt`. :running:

**Comment by gauteh** [comment]
c-alpha writes on februar 9, 2018 19:15:
> Many thanks for the `GetPrerequisites` pointer! Now updating the `CMakeLists.txt`. :running:
> 

Cool! Do you plan to submit a new PR?

**Comment by c-alpha** [comment]
I’ve made a new branch, so can submit a new PR if you prefer, or post a patch here?

  --alex

-- 
www.condition-alpha.com / @c_alpha

**Comment by gauteh** [comment]
Doesn't matter much, just point me to the changes somehow :)

-g

**Comment by c-alpha** [comment]
PR #471

**Comment by c-alpha** [comment]
Cool, many thanks!

**Pull request merged**
