### PR TITLE
PR #470 cmake check nm gmime

### PR DESCRIPTION
**Pull request by c-alpha**
This should ensure the alignment of the `gmime` versions between `notmuch` and `astroid`.

### CODE REVIEW

**Comment by gauteh** [comment]
Nice, looks good. I see you removed USE_GMIME_26, could you please 
restore it? Or are you automatically selecting the same GMime version as 
notmuch now?

c-alpha writes on februar 12, 2018 18:34:

**Comment by c-alpha** [comment]
On 2018-02-12, at 20:33 , Gaute Hope <notifications@github.com> wrote:

> [...]
> Or are you automatically selecting the same GMime version as 
> notmuch now?
> [...]

Yes, that's the case. `find_package(Notmuch)` also sets the variable `Notmuch_GMIME_VERSION`, which holds the three-tier version number of the gmime library that the notmuch library links against.

Since in most situations, a two-tier version number is needed, I introduced a new variable `GMIME_MAJOR_MINOR`.

So astroid is always built against the same gmime version as notmuch, and the gir introspection also uses that same gmime version.

As a byproduct, the new `FindNotmuch.cmake` also sets the variable `Notmuch_VERSION`, which holds the version of the notmuch shared lib (currently "5.0.0").

It seemed that `USE_GMIME_26` only had the purpose of forcing a particular gmime version to align with what had been used to build notmuch? Hence I removed it, because the versions are now aligned automatically.

**Comment by gauteh** [comment]
c-alpha writes on februar 13, 2018 13:55:
> On 2018-02-12, at 20:33 , Gaute Hope <notifications@github.com> wrote:
> 
>> [...]
>> Or are you automatically selecting the same GMime version as 
>> notmuch now?
>> [...]
> 
> Yes, that's the case. `find_package(Notmuch)` also sets the variable `Notmuch_GMIME_VERSION`, which holds the three-tier version number of the gmime library that the notmuch library links against.
> 
> [...]
>
> It seemed that `USE_GMIME_26` only had the purpose of forcing a particular gmime version to align with what had been used to build notmuch? Hence I removed it, because the versions are now aligned automatically.

Good! This is a nice solution. We have to print make it clear from cmake 
output which gmime version is used and that it is acquired from notmuch. 
I'll take a look later on!

**Comment by gauteh** [comment]
Getting the following error:


-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Available config types: Debug;Release
CMake Warning at CMakeLists.txt:26 (message):
  No CMAKE_BUILD_TYPE value specified, defaulting to Debug.


-- Building astroid v0.11-8-g437d7f12
-- Found Notmuch 5.0.0
-- Looking for notmuch_database_index_file
-- Looking for notmuch_database_index_file - found
CMake Warning at cmake/FindNotmuch.cmake:79 (message):
  [ FindNotmuch.cmake:79 ] Failed to determine needed libgmime version
  number, please report this as a bug.
Call Stack (most recent call first):
  CMakeLists.txt:79 (find_package)


-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtkmm-3.0>=3.10'
--   Found gtkmm-3.0, version 3.22.2
-- Checking for module 'glibmm-2.4'
--   Found glibmm-2.4, version 2.54.1
-- Checking for module 'webkitgtk-3.0'
--   Found webkitgtk-3.0, version 2.4.11
-- Checking for module 'libsass'
--   Found libsass, version na
-- Checking for module 'gmime-unknown>=unknown'
--   No package 'gmime-unknown' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:91 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/gaute/dev/mail/notm/astroid/build2/CMakeFiles/CMakeOutput.log".

**Comment by c-alpha** [comment]
Duh!

The offending block in `cmake/FindNotmuch.cmake` is at the end of the file:
```cmake
# GMime version notmuch was linked against
include (GetPrerequisites)
GET_PREREQUISITES(${Notmuch_LIBRARY} _notmuch_prerequisites 1 0 "" "")
set (Notmuch_GMIME_VERSION  "unknown")
if (_notmuch_prerequisites)
  string (REGEX REPLACE
    ".*gmime.*([0-9]+\.[0-9]+\.[0-9]+).*"
    "\\1" Notmuch_GMIME_VERSION ${_notmuch_prerequisites})
else()
  message(WARNING "[ FindNotmuch.cmake:${CMAKE_CURRENT_LIST_LINE} ] "
    "Failed to determine needed libgmime version number, please report this as a bug.")
endif()
unset (_notmuch_prerequisites)
```
Can you insert the line
```cmake
message (STATUS "_notmuch_prerequisites = ${_notmuch_prerequisites}")
```
 just before the `if`, and post the output here, please?

**Comment by gauteh** [comment]
c-alpha writes on februar 13, 2018 15:09:
> Duh!
> 
> The offending block in `cmake/FindNotmuch.cmake` is at the end of the file:
> ```cmake
> # GMime version notmuch was linked against
> include (GetPrerequisites)
> GET_PREREQUISITES(${Notmuch_LIBRARY} _notmuch_prerequisites 1 0 "" "")
> set (Notmuch_GMIME_VERSION  "unknown")
> if (_notmuch_prerequisites)
>   string (REGEX REPLACE
>     ".*gmime.*([0-9]+\.[0-9]+\.[0-9]+).*"
>     "\\1" Notmuch_GMIME_VERSION ${_notmuch_prerequisites})
> else()
>   message(WARNING "[ FindNotmuch.cmake:${CMAKE_CURRENT_LIST_LINE} ] "
>     "Failed to determine needed libgmime version number, please report this as a bug.")
> endif()
> unset (_notmuch_prerequisites)
> ```
> Can you insert the line
> ```cmake
> message (STATUS "_notmuch_prerequisites = ${_notmuch_prerequisites}")
> ```
>  just before the `if`, and post the output here, please?
> 

This gives "_notmuch_prerequisites = ", I had to also include system 
libs. However, if I change line 72 to:


GET_PREREQUISITES(${Notmuch_LIBRARY} _notmuch_prerequisites FALSE FALSE "" "")

I still get an error, but different output and the var is at least 
populated:


❯ build2 471* cmake ..
-- Available config types: Debug;Release
-- The CMake build type is: Debug
-- Building astroid v0.11-8-g437d7f12
-- Found Notmuch 5.0.0
-- _notmuch_prerequisites = /usr/lib/libassuan.so.0;/usr/lib/libblkid.so.1;/usr/lib/libc.so.6;/usr/lib/libdl.so.2;/usr/lib/libffi.so.6;/usr/lib/libgcc_s.so.1;/usr/lib/libgio-2.0.so.0;/usr/lib/libglib-2.0.so.0;/usr/lib/libgmime-3.0.so.0;/usr/lib/libgmodule-2.0.so.0;/usr/lib/libgobject-2.0.so.0;/usr/lib/libgpg-error.so.0;/usr/lib/libgpgme.so.11;/usr/lib/libidn.so.11;/usr/lib/libm.so.6;/usr/lib/libmount.so.1;/usr/lib/libpcre.so.1;/usr/lib/libpthread.so.0;/usr/lib/libresolv.so.2;/usr/lib/librt.so.1;/usr/lib/libstdc++.so.6;/usr/lib/libtalloc.so.2;/usr/lib/libuuid.so.1;/usr/lib/libxapian.so.30;/usr/lib/libz.so.1;/usr/lib64/ld-linux-x86-64.so.2
-- Checking for module 'gmime-/usr/lib/libassuan.so.0/usr/lib/libblkid.so.1/usr/lib/libc.so.6/usr/lib/libdl.so.2/usr/lib/libffi.so.6/usr/lib/libgcc_s.so.1/usr/lib/libgio-2.0.so.0/usr/lib/libglib-2.0.so.0/usr/lib/libgmime-3.0.so.0/usr/lib/libgmodule-2.0.so.0/usr/lib/libgobject-2.0.so.0/usr/lib/libgpg-error.so.0/usr/lib/libgpgme.so.11/usr/lib/libidn.so.11/usr/lib/libm.so.6/usr/lib/libmount.so.1/usr/lib/libpcre.so.1/usr/lib/libpthread.so.0/usr/lib/libresolv.so.2/usr/lib/librt.so.1/usr/lib/libstdc++.so.6/usr/lib/libtalloc.so.2/usr/lib/libuuid.so.1/usr/lib/libxapian.so.30/usr/lib/libz.so.1/usr/lib64/ld-linux-x86-64.so.2>=/usr/lib/libassuan.so.0/usr/lib/libblkid.so.1/usr/lib/libc.so.6/usr/lib/libdl.so.2/usr/lib/libffi.so.6/usr/lib/libgcc_s.so.1/usr/lib/libgio-2.0.so.0/usr/lib/libglib-2.0.so.0/usr/lib/libgmime-3.0.so.0/usr/lib/libgmodule-2.0.so.0/usr/lib/libgobject-2.0.so.0/usr/lib/libgpg-error.so.0/usr/lib/libgpgme.so.11/usr/lib/libidn.so.11/usr/lib/libm.so.6/usr/lib/libmount.so.1/usr/lib/libpcre.so.1/usr/lib/libpthread.so.0/usr/lib/libresolv.so.2/usr/lib/librt.so.1/usr/lib/libstdc++.so.6/usr/lib/libtalloc.so.2/usr/lib/libuuid.so.1/usr/lib/libxapian.so.30/usr/lib/libz.so.1/usr/lib64/ld-linux-x86-64.so.2'
--   No package 'gmime-/usr/lib/libassuan.so.0/usr/lib/libblkid.so.1/usr/lib/libc.so.6/usr/lib/libdl.so.2/usr/lib/libffi.so.6/usr/lib/libgcc_s.so.1/usr/lib/libgio-2.0.so.0/usr/lib/libglib-2.0.so.0/usr/lib/libgmime-3.0.so.0/usr/lib/libgmodule-2.0.so.0/usr/lib/libgobject-2.0.so.0/usr/lib/libgpg-error.so.0/usr/lib/libgpgme.so.11/usr/lib/libidn.so.11/usr/lib/libm.so.6/usr/lib/libmount.so.1/usr/lib/libpcre.so.1/usr/lib/libpthread.so.0/usr/lib/libresolv.so.2/usr/lib/librt.so.1/usr/lib/libstdc++.so.6/usr/lib/libtalloc.so.2/usr/lib/libuuid.so.1/usr/lib/libxapian.so.30/usr/lib/libz.so.1/usr/lib64/ld-linux-x86-64.so.2' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:91 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/gaute/dev/mail/notm/astroid/build2/CMakeFiles/CMakeOutput.log".

**Comment by c-alpha** [comment]
Ah, I see. It's a shared lib naming convention issue. I'll fix it.

**Comment by c-alpha** [comment]
@gauteh, does 952ef53b6c3521c51f865561a0bdc532f5b68dda make it work for you?

**Comment by gauteh** [comment]
```
❯ build2 471 cmake .. -GNinja
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Available config types: Debug;Release
CMake Warning at CMakeLists.txt:26 (message):
  No CMAKE_BUILD_TYPE value specified, defaulting to Debug.


-- Building astroid v0.11-9-g952ef53b
-- Found Notmuch 5.0.0
-- Looking for notmuch_database_index_file
-- Looking for notmuch_database_index_file - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for module 'gtkmm-3.0>=3.10'
--   Found gtkmm-3.0, version 3.22.2
-- Checking for module 'glibmm-2.4'
--   Found glibmm-2.4, version 2.54.1
-- Checking for module 'webkitgtk-3.0'
--   Found webkitgtk-3.0, version 2.4.11
-- Checking for module 'libsass'
--   Found libsass, version na
-- Checking for module 'gmime-2.0>=2.0.0'
--   No package 'gmime-2.0' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:91 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/gaute/dev/mail/notm/astroid/build2/CMakeFiles/CMakeOutput.log".
```

Output from `ldd /usr/local/lib/libnotmuch.so`:

```
❯ lib ldd libnotmuch.so
ldd: warning: you do not have execution permission for `./libnotmuch.so'
        linux-vdso.so.1 (0x00007ffce84b3000)
        libgmime-3.0.so.0 => /usr/lib/libgmime-3.0.so.0 (0x00007f7786ee2000)
        libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f7786c8d000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f7786978000)
        libtalloc.so.2 => /usr/lib/libtalloc.so.2 (0x00007f7786763000)
        libxapian.so.30 => /usr/lib/libxapian.so.30 (0x00007f7786355000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f7785fce000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f7785db7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f7785a00000)
        libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f7785654000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f778543d000)
        libgpgme.so.11 => /usr/lib/libgpgme.so.11 (0x00007f77851f8000)
        libidn.so.11 => /usr/lib/libidn.so.11 (0x00007f7784fc4000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f7784da6000)
        libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f7784b9d000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f778492a000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f7784722000)
        libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f778451b000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f77841cf000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f778738d000)
        libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f7783fcb000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f7783db4000)
        libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f7783b5e000)
        libassuan.so.0 => /usr/lib/libassuan.so.0 (0x00007f778394b000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f7783736000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f7783532000)
        libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f77832e4000)

```

**Comment by c-alpha** [comment]
Seems there was too much regex magic. Could you try again with e60a8b17109f2c200441f8ce72e327c5bb82b8ba, please?

**Comment by gauteh** [comment]
Seems to work now!

```

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Available config types: Debug;Release
CMake Warning at CMakeLists.txt:26 (message):
  No CMAKE_BUILD_TYPE value specified, defaulting to Debug.


-- Building astroid v0.11-10-ge60a8b17
-- Found Notmuch 5.0.0
-- Looking for notmuch_database_index_file
-- Looking for notmuch_database_index_file - found
-- Notmuch was built against GMime 3.0.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for module 'gtkmm-3.0>=3.10'
--   Found gtkmm-3.0, version 3.22.2
-- Checking for module 'glibmm-2.4'
--   Found glibmm-2.4, version 2.54.1
-- Checking for module 'webkitgtk-3.0'
--   Found webkitgtk-3.0, version 2.4.11
-- Checking for module 'libsass'
--   Found libsass, version na
-- Checking for module 'gmime-3.0>=3.0.0'
--   Found gmime-3.0, version 3.2.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   log_setup
--   log
--   thread
--   date_time
--   system
--   regex
--   chrono
--   atomic
-- Checking for module 'vte-2.91'
--   Found vte-2.91, version 0.50.3
-- Looking for sass_context.h
-- Looking for sass_context.h - not found
-- Looking for sass/context.h
-- Looking for sass/context.h - found
-- Checking for module 'gobject-introspection-1.0'
--   Found gobject-introspection-1.0, version 1.54.1
-- Checking for module 'libpeas-1.0>=1.0.0'
--   Found libpeas-1.0, version 1.22.0
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gaute/dev/mail/notm/astroid/build2

```

**Comment by gauteh** [comment]
Is this ready to merge?

**Comment by c-alpha** [comment]
On 2018-02-18, at 11:32 , Gaute Hope <notifications@github.com> wrote:

> Is this ready to merge?

Yes, it is.

Many thanks for having been the guinea pig! ;-)

**Comment by gauteh** [comment]
Thanks, merged!

**Pull request closed without merging**
