### PR TITLE
take DESTDIR environment variable into account (if and when set) when installing symlinks

### PR DESCRIPTION
**Pull request by c-alpha**
This should address astroidmail/astroid#514.

I myself cannot test at this time because of astroidmail/homebrew-astroid#11 (no WebKitGTK+ on macOS at the moment). **So please do let me know whether this works and solves the issue.**

### CODE REVIEW

**Comment by gauteh** [comment]
Thanks, merged! :)

**Comment by Hello71** [comment]
I don't get why it has to check DESTDIR. `//a` is the same as `/a` anyways (for the source of symlink).

**Comment by gauteh** [comment]
`/a/b/` is not the same as `a/b/`

**Comment by Hello71** [comment]
still not sure it works right, but I don't know how cmake install works, so I'll assume it's right and report back if it breaks for me.

**Pull request closed without merging**
