### PR TITLE
Fix segmentation fault when quitting (#636)

### PR DESCRIPTION
**Pull request by Liblor**
I added a redundant `include` to the main for readability, I hope that's fine for you.

### CODE REVIEW

**Comment by Liblor** [comment]
If I understand correctly you try to avoid stuff like:
```
6: the current user preferred locale is: en_US.utf8
6: the current user preferred locale is: en_US.utf8
6: the current user preferred locale is: en_US.utf8
```
unfortunately it doesn't look like this patch helps. I diffed the output of `ctest --verbose` and didn't see any noticeable differences

**Comment by gauteh** [comment]
On Thu, May 30, 2019 at 11:28 PM Loris Reiff <notifications@github.com>
wrote:

> If I understand correctly you try to avoid stuff like:
>
> 6: the current user preferred locale is: en_US.utf8
> 6: the current user preferred locale is: en_US.utf8
> 6: the current user preferred locale is: en_US.utf8
>
> unfortunately it doesn't look like this patch helps. I diffed the output
> of ctest --verbose and didn't see any noticeable differences
>
Hm, weird, it worked here. Compared to master or compared to your PR? I
believe on master the duplicate lines should be gone. If I remember
correctly that was the purpose of the original commit.

**Comment by Liblor** [comment]
I just had a look at my bash history, I compared the patched PR to master, of course there's no difference... I guess I was a little tired. Sorry about the inconvenience... The above mentioned duplicated lines are also present on master.

**Comment by gauteh** [comment]
Thanks, merged!

**Pull request merged**
