### PR TITLE
Cb tag jump

### PR DESCRIPTION
**Pull request by gauteh**
* Colors for tag-editor
* Better jump and delete between tags when editing

http://imgur.com/a/hw0qB

### CODE REVIEW

**Comment by mxmehl** [comment]
The colours are very nice. The only thing I don't like here is that as soon as the tags are modified (add or delete a character), the font colour changes to white instead of black. This makes it hard to read.

The jump between the tags (using the left arrow key?) doesn't work for me.

**Comment by gauteh** [comment]
Max writes on juli 17, 2017 19:03:
> The colours are very nice. The only thing I don't like here is that as soon as the tags are modified (add or delete a character), the font colour changes to white instead of black. This makes it hard to read.
> 
> The jump between the tags (using the left arrow key?) doesn't work for me.

Yeah, there's a bug about the font color still (and the color of the 
last tag). Not sure about the jumping yet, I get to the right one when I 
use Alt-Left. Thinking about moving it to Ctrl+h. Also, I'd like to 
select the whole tag when moving left so that the whole tag can be 
easily removed with just Backspace. Making it easier to remove tags.

**Comment by gauteh** [comment]
Gaute Hope writes on juli 17, 2017 19:35:
> Max writes on juli 17, 2017 19:03:
>> The colours are very nice. The only thing I don't like here is that as soon as the tags are modified (add or delete a character), the font colour changes to white instead of black. This makes it hard to read.
>> 
>> The jump between the tags (using the left arrow key?) doesn't work for me.
> 
> Yeah, there's a bug about the font color still (and the color of the 
> last tag). Not sure about the jumping yet, I get to the right one when I 
> use Alt-Left. Thinking about moving it to Ctrl+h. Also, I'd like to 
> select the whole tag when moving left so that the whole tag can be 
> easily removed with just Backspace. Making it easier to remove tags.
> 
> 

font color should be fixed, as well as colors for unicode chars

**Comment by gauteh** [comment]
Pushed colorful tags to master, tag-jump not yet.

**Comment by gauteh** [comment]
branch copy here: https://github.com/gauteh/astroid/tree/cb-tag-jump

**Pull request closed without merging**
