### PR TITLE
Trying to implement run hooks on thread view see #29

### PR DESCRIPTION
**Pull request by hugoroy**
This is as far as I could get :-) haha
Of course it does not work.

### CODE REVIEW

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 21:56:
> This is as far as I could get :-) haha
> Of course it does not work. 

Not bad :)

You forgot a few includes and passed a message object, rather than the
message-id which is what should be passed here, here's some changes,
does that work:

```
diff --git a/src/modes/thread_view/thread_view.cc b/src/modes/thread_view/thread_view.cc
index 55dcfee..f141b22 100644
--- a/src/modes/thread_view/thread_view.cc
+++ b/src/modes/thread_view/thread_view.cc
@@ -24,10 +24,12 @@
 # include "utils/vector_utils.hh"
 # include "utils/ustring_utils.hh"
 # include "utils/gravatar.hh"
+# include "utils/cmd.hh"
 # ifndef DISABLE_PLUGINS
   # include "plugin/manager.hh"
 # endif
 # include "actions/action.hh"
+# include "actions/cmdaction.hh"
 # include "actions/tag_action.hh"
 # include "actions/toggle_action.hh"
 # include "modes/mode.hh"
@@ -2625,10 +2627,10 @@ namespace Astroid {
 	[&] (Key, ustring cmd) {
           if (!edit_mode && focused_message) {
 
-            cmd = ustring::compose (cmd, new NotmuchMessage(focused_message));
+            cmd = ustring::compose (cmd, focused_message->mid);
 
             astroid->actions->doit (refptr<Action> (new CmdAction (
-		   Cmd ("thread_view.run", cmd), (focused_message), "")));
+		   Cmd ("thread_view.run", cmd), "", focused_message->mid)));
           }
 
           return true;
```

**Comment by gauteh** [comment]
Actually, we should probably pass both the thread_id as %1 and message_id as %2 so that the hook can use either or both as it wants:
```
diff --git a/src/actions/cmdaction.cc b/src/actions/cmdaction.cc
index 783efe8..6500b72 100644
--- a/src/actions/cmdaction.cc
+++ b/src/actions/cmdaction.cc
@@ -24,12 +24,14 @@ namespace Astroid {
   }
 
   void CmdAction::emit (Db * db) {
-    if (thread_id != "") {
-      astroid->actions->emit_thread_updated (db, thread_id);
-    }
-
     if (mid != "") {
+      // will also emit thread_changed
       astroid->actions->emit_message_updated (db, mid);
+      return;
+    }
+
+    if (thread_id != "") {
+      astroid->actions->emit_thread_updated (db, thread_id);
     }
   }
 }
diff --git a/src/modes/thread_view/thread_view.cc b/src/modes/thread_view/thread_view.cc
index 55dcfee..6a5f30e 100644
--- a/src/modes/thread_view/thread_view.cc
+++ b/src/modes/thread_view/thread_view.cc
@@ -24,10 +24,12 @@
 # include "utils/vector_utils.hh"
 # include "utils/ustring_utils.hh"
 # include "utils/gravatar.hh"
+# include "utils/cmd.hh"
 # ifndef DISABLE_PLUGINS
   # include "plugin/manager.hh"
 # endif
 # include "actions/action.hh"
+# include "actions/cmdaction.hh"
 # include "actions/tag_action.hh"
 # include "actions/toggle_action.hh"
 # include "modes/mode.hh"
@@ -2625,10 +2627,10 @@ namespace Astroid {
 	[&] (Key, ustring cmd) {
           if (!edit_mode && focused_message) {
 
-            cmd = ustring::compose (cmd, new NotmuchMessage(focused_message));
+            cmd = ustring::compose (cmd, focused_message->tid, focused_message->mid);
 
             astroid->actions->doit (refptr<Action> (new CmdAction (
-		   Cmd ("thread_view.run", cmd), (focused_message), "")));
+		   Cmd ("thread_view.run", cmd), focused_message->tid, focused_message->mid)));
           }
 
           return true;
```

**Comment by hugoroy** [comment]
Yes! it works! \o/

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 22:51:
> Yes! it works! \o/

Merged, thanks.

**Pull request closed without merging**
