### PR TITLE
Webkit2js

### PR DESCRIPTION
**Pull request by gauteh**
(replaces #402 )

### CODE REVIEW

**Comment by Ramblurr** [comment]
Do you want to create a legacy branch for fixes/updates to the webkit1 version? As if this goes into master, you can't release until we finish the JS implementation. I've had some time recently, but I'm not sure how much longer it will take or if it will be done sooner rather than later.

**Comment by gauteh** [comment]
Yes, probably - but we're starting to get quite a bit of trouble with webkit1.

**Comment by gauteh** [comment]
I feel like message loading and display is a bit slow. Is this just an artifact of the inspector window and debugging or do you experience the same?

**Comment by gauteh** [comment]
Now closing in favor of the merged #455. Thanks for the massive effort!

**Pull request closed without merging**
