### PR TITLE
thread-index: remove marked icon, move other icons to tag list

### PR DESCRIPTION
**Pull request by gauteh**
Goal is to make thread-index a bit better, hope to get rid of the icons on the left which are often left empty.

* Uses background color to indicate marked messages, thread-view must be updated to be consistent. Color is really crap at the moment. Suggestions appreciated.

### CODE REVIEW

**Comment by gauteh** [comment]
Thanks, that looks much better. (btw didn't realize you had made the changes yourself somehow before after I pushed the new commit)

**Comment by gauteh** [comment]
Check out latest: icons have been moved to tag line and you can now configure your own tag to image maps using e.g.:
```
            "tag_images" : {
              "bra" : "/usr/share/icons/Humanity/status/48/sunny.svg"
            }
```

under `thread_index.cell` in the config.

2017-05-18-115047_761x800_scrot

**Comment by mxmehl** [comment]
Sweet changes, but I'm not really happy with moving the flagged icon to the tags. This way, I will often overlook them.

Would it be possible to have a slightly different background for flagged messages? Or some other way to recognize them at first sight?

Regarding the attachment icon, the current solution is fine for me. I often don't specifically look for attachments so it's not that critical whether I see it at first sight when skimming over a long list of threads.

**Comment by gauteh** [comment]
Good point about the flagged icon. Might be too much or confusing with marked to use a backgronud color, was thinking about underlining, but i think that gets messy. suggestions welcome.

**Comment by gauteh** [comment]
Added some padding before the date field.

**Comment by mxmehl** [comment]
It may be my unnatural sense of order but the attachment icons disturb the beautiful vertical tab line ;)

http://i.imgur.com/ry2nqeU.png

Can we move the attachment/flagged icons behind the tags? Furthermore, the attachment icon is normally less important than all the tags.

**Comment by gauteh** [comment]
Max writes on mai 18, 2017 23:02:
> It may be my unnatural sense of order but the attachment icons disturb the beautiful vertical tab line ;)
> 
> http://i.imgur.com/ry2nqeU.png
> 
> Can we move the attachment/flagged icons behind the tags? Furthermore, the attachment icon is normally less important than all the tags.

Indeed, that doesn't look very good. I usually have too many tags, so I
wouldn't see the icons in that case..

**Comment by mxmehl** [comment]
I don't know how to proceed here. The current space-saving behaviour contradicts my wish for a clear vertical line in front of the tags, and your wish to have the flagged/attachment icons in front of the taglist...

**Comment by mxmehl** [comment]
Can you push the marked messages to master while we think about how to solve the flagged/attachment conflict?

**Comment by gauteh** [comment]
Max writes on september 3, 2017 14:52:
> Can you push the marked messages to master while we think about how to solve the flagged/attachment conflict?

Yes, but need some good colors for marked messages. Suggestions?

**Comment by gauteh** [comment]
Branch copy here: https://github.com/gauteh/astroid/tree/ti-dabblings

**Pull request closed without merging**
