### PR TITLE
Remove focus style and style attachments

### PR DESCRIPTION
**Pull request by hugoroy**
I would also suggest serious change to the UI of showing information regarding crypto.

### CODE REVIEW

**Comment by gauteh** [comment]
It seems that long links are not wrapped, was this the behavior previously as well?
2016-08-28-160832_1200x1521_scrot

**Comment by hugoroy** [comment]
↪ août 28, 2016 4:10 — Gaute Hope:
> It seems that long links are not wrapped, was this the behavior previously as well?
> 2016-08-28-160832_1200x1521_scrot
> 

I don't remember, but I do not see how these commits would have affected this.

The last commit should fix that :)

**Comment by hugoroy** [comment]
@gauteh I think this is ready now :-)

**Comment by gauteh** [comment]
Hugo Roy writes on september 1, 2016 20:32:
> @gauteh I think this is ready now :-)

Thanks, merged.

**Pull request closed without merging**
