### PR TITLE
consistent editing see issue #461

### PR DESCRIPTION
**Pull request by hugoroy**

### CODE REVIEW

**Comment by gauteh** [comment]
Does this mean that we can drop the C+space binding in edit mode?

**Comment by hugoroy** [comment]
This is for attachments, right?

I think so, yes :-)

**Comment by gauteh** [comment]
Hugo Roy writes on februar 5, 2018 16:23:
> This is for attachments, right?
> 
> I think so, yes :-)
> 

Yes, and the HTML part when composing markdown messages - or forwarding 
mime-messages.

**Comment by gauteh** [comment]
So I think we need:

* `e` is always edit
* `E` is always expand (not implemented yet)
* `Enter` is always activate (open or expand)

Am I missing some functionality now?

**Comment by mxmehl** [comment]
`E` is also used to switch the encryption in new message view.

**Comment by gauteh** [comment]
Haven't forgotten this, but super-busy atm so will look into this in time. Still needs some clarification I think (re @mxmehl comment) and updates.

**Pull request closed without merging**
