### PR TITLE
em: Close page automatically after successful send

### PR DESCRIPTION
**Pull request by mrvdb**
Add configure option: `mail.close_on_success`

### CODE REVIEW

**Comment by mxmehl** [comment]
Cool idea! Would it be possible to add a short wait time (2-5 secs for example) and the possibility to skip auto-closing during this time, e.g. by pressing Ctrl-C?

**Comment by mrvdb** [comment]
I'm sure it's technically possible. (sounds pretty similar to the send delay already there)

**Comment by gauteh** [comment]
Nice, maybe we can also add a feature where closing the window while the message is sending (C-w) causes the close_on_successful_send to be set and an small info to be set that it will be closed on sent, and then cycle to the tab which would otherwise get focus if it was closed? 

I have one small concern, if you have accounts where the sent message is not stored (and the email service does not do it for you) you will not have a chance to save the sent message. But I guess that would probably be overly protective..

Either way; I think this can be merged as-is and then the other features can be added later.

**Comment by gauteh** [comment]
Merged.

**Comment by gauteh** [comment]
By the way; please add a section to the configuration reference.

**Comment by mrvdb** [comment]
> By the way; please add a section to the configuration reference.

Push was already waiting, it should be there

**Comment by gauteh** [comment]
Marcel van der Boom writes on mars 6, 2018 18:38:
>> By the way; please add a section to the configuration reference.
> 
> Push was already waiting, it should be there

Great!

**Pull request merged**
