### PR TITLE
Manual page: astroid(1)

### PR DESCRIPTION
**Pull request by Fnux**
As discussed in #397, here is a simple manpage for astroid. Most of the content is extracted from the wiki.

### CODE REVIEW

**Comment by gauteh** [comment]
Thanks, this looks very good! 

I'll see if I can make a processor for CMake, since scdoc is not very 
widely available this will gracefully fail if scdoc is missing. I think 
we should drop or change the man page section in the README to just say along with the note about the wiki: ... or see `man astroid` (requires `scdoc`).

A few comments:

* Notmuch is required (the way it is written now is seems like it is 
  optional).
* Perhaps also refer to gmailieer or to the notmuch wiki in this list
* The environmental variable: ASTROID_DIR can be used to set the path of 
  the local resources. This is mostly for debug purposes or when running 
  directly from source (see examples/astroid). Not sure if this should 
  be documented in the man page.
* The environmental variable: GI_TYPELIB_PATH should be set to the 
  typelib dir when astroid is not installed to be able to use plugins. 
  Also, not sure if this should be included. It is more of a libpeas 
  thing / gobject-introspection thing.
* The command line option: --log-level is in master which can be used to 
  override the configured log level (options are trace,debug (default),info,warn,error,fatal)

**Comment by Fnux** [comment]
> * The environmental variable: ASTROID_DIR can be used to set the path of
  the local resources. This is mostly for debug purposes or when running
  directly from source (see examples/astroid). Not sure if this should
  be documented in the man page.

What "local resources" are you talking about ? Configuration ?

> * The environmental variable: GI_TYPELIB_PATH should be set to the
  typelib dir when astroid is not installed to be able to use plugins.
  Also, not sure if this should be included. It is more of a libpeas
  thing / gobject-introspection thing.

I don't think it is useful to the end user, and would be more confusing than helping.

**Comment by gauteh** [comment]
Fnux writes on August 8, 2018 13:12:
>> * The environmental variable: ASTROID_DIR can be used to set the path of
>   the local resources. This is mostly for debug purposes or when running
>   directly from source (see examples/astroid). Not sure if this should
>   be documented in the man page.
> 
> What "local resources" are you talking about ? Configuration ?

Theme files (html, scss), webextension, glade files. These are normally 
placed in ~/.config/astroid when user-configured (unrelated to this 
var). So this var can be undocumented.

> 
>> * The environmental variable: GI_TYPELIB_PATH should be set to the
>   typelib dir when astroid is not installed to be able to use plugins.
>   Also, not sure if this should be included. It is more of a libpeas
>   thing / gobject-introspection thing.
> 
> I don't think it is useful to the end user, and would be more confusing than helping.

Agreed.

The page you have written can also be used with `ronn` which is more 
widely available. I think we can use this in the Makefiles if scdoc is 
not avilable.

**Comment by Fnux** [comment]
> Theme files (html, scss), webextension, glade files. These are normally
placed in ~/.config/astroid when user-configured (unrelated to this
var). So this var can be undocumented.

I feel like those files should go in `$XDG_DATA_HOME/astroid` instead of `$XDG_CONFIG_HOME/astroid`. Some user might use the `ASTROID_DIR` environment variable, I will add it to the manpage.

**Comment by Fnux** [comment]
I misunderstood, my bad. Let's ignore ASTROID_DIR.

**Comment by gauteh** [comment]
Fnux writes on August 24, 2018 11:30:
> I misunderstood, my bad. Let's ignore ASTROID_DIR.

Sounds good. Are there any more changes you plan on doing before the PR 
is ready? I probably won't be able to merge it before next week.

**Comment by Fnux** [comment]
That's all :-)

**Comment by gauteh** [comment]
Fnux writes on August 24, 2018 11:40:
> That's all :-)
> 

Merged! The manpage is now built and installed. If scdoc is not 
available ronn is used. I also documented the `$NOTMUCH_CONFIG` variable 
which is now supported (#543, @kyrias).

**Pull request closed without merging**
