### PR TITLE
Drop mark icon: Indicate marked message with background color in thread-index

### PR DESCRIPTION
**Pull request by gauteh**
Only the marked message stuff from #336

### CODE REVIEW

**Comment by yeled** [comment]
:+1:

**Comment by yeled** [comment]
much easier to read now in a busy window:

image

**Comment by mxmehl** [comment]
Colour looks fine for me, thanks!

**Comment by gauteh** [comment]
Good! Merged.

**Comment by gauteh** [comment]
We should maybe update the marked state in thread-view as well to be 
consistent with the thread-index UI. But its not critical.

**Pull request merged**
