### PR TITLE
Quote html parts

### PR DESCRIPTION
**Pull request by gauteh**
Update `mail.reply.quote_processor` to whatever you want to process HTML parts into text when quoting.

#319 and others.

### CODE REVIEW

**Comment by mxmehl** [comment]
Thanks! I tried it and it failed for 3 HTML only mails I tested :(

Nothing happens in the UI after pressing `r`, but in the logfile there is quite some activity.

[Logfile](https://p.mehl.mx/?760a7b3ddd30df3d#/riYuiG/+LWrvUgH7bDLfeXYfmtq/WePTYbQwfAXLaU=)

**Comment by gauteh** [comment]
Thanks, you have lynx installed? Also just so you know the content of the
html is in the log in case it is private.

ons. 3. apr. 2019 kl. 17:57 skrev Max <notifications@github.com>:

**Comment by gauteh** [comment]
Please try the latest version again, moved to w3m which seems to be a little bit more robust. But maybe not as nice output.

**Comment by jimcheetham** [comment]
This is working for me (once I realised that my startup options were being *invisibly ignored* because there was an existing astroid session running in a different desktop).

Also, because you're execve() the call, I can successfully invoke an arbitrary pipeline by taking responsibility for using "bash -c 'cmd | cmd'" if I want to.

I would *love* to be able to use something like this on message preview, instead of having to explicitly invoke my preview option ...

**Comment by gauteh** [comment]
Great! What do you mean with preview and preview option?

**Comment by jimcheetham** [comment]
As per my original #319; but where I originally said that "Not having them render HTML by default seems sensible" I'm sort of less comfortable with that over time. Possibly not the right conversation to have on a patch that addresses the reply function though.

**Comment by gauteh** [comment]
You can choose to have the HTML part to be shown by default, think it is `thread_view.preferred_type` or `thread_view.preferred_html_only` (the latter opens html parts of HTML only part, otherwise uses the text part). Just to make sure, you do know you can activate/press enter on the html part to open it?

**Comment by gauteh** [comment]
Something that would be nice would be to also include attachments (like images) and have the CID be updated accordingly (e.g. #597). But might not be any point without converting to markdown.

**Comment by jimcheetham** [comment]
Thanks, I'll check later. Yes, I can currently read messages that have no text/plain portion by selecting the text/html part, and pressing enter, but I hadn't looked for a 'display by default' option recently, so I'll double-check.

**Comment by gauteh** [comment]
@mxmehl: did you have a chance to try again?

**Comment by mxmehl** [comment]
Yes, I tried it today and it works! w3m made the difference, lynx dump only worked with very simple (and valid) HTML, for HTML-only newsletters which tend to contain a lot of inline CSS and invalid HTML, it seems to be unstable.

**Comment by gauteh** [comment]
Nice, what error did you get with lynx -dump -stdin?

**Comment by mxmehl** [comment]
> Nice, what error did you get with lynx -dump -stdin?

None. Nothing happened in the UI, and the log looked the same as in my first comment. It only worked for simple (valid?) HTML. I can forward you one of the failing emails if you want

**Comment by gauteh** [comment]
Ok, I think I have one message in the test suite where I get the same error. Looks like a conversion error when lynx fails.. either way we should handle whatever output the processor throws at us.

**Comment by gauteh** [comment]
Merged. Not working for lynx, but seems to work well with w3m. Ideally need to fix conversion error at later time.

**Comment by l1gi** [comment]
I have hit probably the same issue.

Log file: https://cloud.tekkirk.org/index.php/s/dJHM6NbLZtc597T

> [17:33:15] [0x00000008099b5000] [M] [error] astroid needs an UTF-8 locale! this is probably not going to work.
> ...
> [17:33:23] [0x00000008099b5000] [M] [info] cmd: running: w3m -dump -T text/html
> [17:33:23] [0x00000008099b5000] [M] [debug] em: deconstruct.
> [17:33:23] [0x00000008099b5000] [M] [info] db: closing db.
> [17:33:23] [0x00000008099b5000] [M] [debug] db: ro: waiting for lock to close..
> [17:33:23] [0x00000008099b5000] [M] [debug] db: ro: closing..
> [17:33:23] [0x00000008099b5000] [M] [debug] mt: destruct.
> [17:33:23] [0x00000008099b5000] [M] [debug] ms: deconstruct
> [17:33:23] [0x00000008099b5000] [M] [debug] chunk: deconstruct.
> 
> (<unknown>:44954): glibmm-CRITICAL **: 17:33:23.538: 
> unhandled exception (type Glib::Error) in signal handler:
> domain: g_convert_error
> code  : 1
> what  : Invalid byte sequence in conversion input

Mail: https://cloud.tekkirk.org/index.php/s/n5oSGPi2PfwjYzY

**Comment by gauteh** [comment]
See the first quoted line, can you try with an utf-8 locale?


ons. 14. aug. 2019, 17:41 skrev l1gi <notifications@github.com>:

**Comment by l1gi** [comment]
Yes, that was the reason why I pasted it. My previous locale setting:

```
LANG=
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

After I have set LANG also to en_US.UTF-8 it started to work. I thought my setting is valid, so maybe it is not.

Thanks much for your time.

**Comment by gauteh** [comment]
Ok, I tried to rely on glib there so I hope it is correctly interpreting
your env. The settings might affect the output from the HTML to text
processor for quoting.

tor. 15. aug. 2019, 09:56 skrev l1gi <notifications@github.com>:

**Pull request merged**
