### PR TITLE
em: catch missing fields and mentions of attachments before sending

### PR DESCRIPTION
**Pull request by gauteh**
#245

### CODE REVIEW

**Comment by mxmehl** [comment]
Thanks! But how can I define multiple words? My config looks like this:

`"attachment_words": "attachment,attached,anbei,anhang,angehängt"`

I only get the error message when using the whole string in the mail. Content like `see my attachment here` doesn't trigger a warning with this config. I also tried semicolons.

The warning when using no `To` worked fine for me.

**Comment by gauteh** [comment]
Thanks for testing. 

I changed it to use ',' as separator, please try again. Also, incomplete
words will be matched. So just using 'attach' rather than attachment and
attached will be faster.

**Comment by mxmehl** [comment]
Much better, thanks!

My last wish: could you please make it case-insensitive?

**Comment by gauteh** [comment]
Max writes on desember 24, 2016 16:55:
> Much better, thanks!
> 
> My last wish: could you please make it case-insensitive?

Should work now!

**Comment by mxmehl** [comment]
>> My last wish: could you please make it case-insensitive?
>
> Should work now!

It does! Thanks for the christmas present ;)

**Comment by gauteh** [comment]
Max writes on desember 24, 2016 22:50:
>>> My last wish: could you please make it case-insensitive?
>>
>> Should work now!
> 
> It does! Thanks for the christmas present ;)
> 

Merged. merry christmas :)

**Pull request closed without merging**
